import turtle

screen = turtle.Screen()
screen.bgcolor("lightblue")
screen.title("Солнышко")
sun = turtle.Turtle()
sun.speed(8)
sun.pensize(3)
sun.color("yellow")
sun.begin_fill()
sun.circle(100)
sun.end_fill()
sun.color("orange")
sun.pensize(4)
sun.penup()
sun.goto(0, 100)  
sun.setheading(90)  
sun.pendown()
for _ in range(12):
    sun.penup()
    sun.forward(100)  
    sun.pendown()
    sun.forward(50)   
    sun.penup()
    sun.backward(150) 
    sun.pendown()
    sun.right(30)     

sun.penup()
sun.goto(-30, 150)
sun.pendown()
sun.color("black")
sun.begin_fill()
sun.circle(10)
sun.end_fill()
sun.penup()
sun.goto(30, 150)
sun.pendown()
sun.begin_fill()
sun.circle(10)
sun.end_fill()
sun.penup()
sun.goto(-40, 120)
sun.pendown()
sun.setheading(-60)
sun.circle(40, 120)
sun.hideturtle()
screen.exitonclick()